######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 16 11:16:28 2010
######################################################################

TEMPLATE = app
TARGET = textEditor
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets core printsupport

# Input
HEADERS += finddialog.h mainwindow.h
SOURCES += finddialog.cpp main.cpp mainwindow.cpp
RESOURCES += resource.qrc
